

Q WA function to take list as parameter and print all numbers of given list which are divisible by 11

In [4]:
def fn(ll):
  lis_11=list()
  lis_11=[o for o in ll if o%11==0]
  return lis_11

l=[11,22,75,7,4,8,1,7,88]
print(fn(l))

[11, 22, 88]

Q WA function to take string as parameter
Check if string is palindrome are not
If palindrome return 1
if not palindrome return 0

In [6]:
def palindrome(s):
  if s==s[::-1]:
    return 1
  else:
    return 0

string='nitin'
print(palindrome(string))

1

In [ ]:
def reverse_string(input_str):
    reversed_str = ''.join(reversed(input_str))
    return reversed_str

# Example usage:
original_str = "Hello, World!"
reversed_str = reverse_string(original_str)

print(f"Original String: {original_str}")
print(f"Reversed String: {reversed_str}")

In [34]:
def palindrome(s):
  start=0
  end=len(s)-1

  while start < end:
    if s[start]!=s[end]:
      return False
    start+=1
    end-=1
  return True

a=palindrome('ramar')
if a:
  print('palindrome')
else:
  print('not palindrome')

palindrome

Q WA function to check if number is prime or not. Return True if number is prime and false if number not prime.

In [20]:
def prime(num):
  if num==1:
    return False
  elif num>1:
    for i in range(2,num):
      if num%i==0:
        return False
    else:
        return True

number=13
print(prime(number))

True

 WA function to take a string as parameter. Print its alternate characters starting from 2nd character

In [23]:
def alternate(string1):
  print(string1[1::2])

alternate('prajwal')

rja

Q WA function to take a dictionary as parameter. Print value of key "name" if key "rollno" is having value 100

In [24]:
def keyroll(d):
  for i,j in d.items():
    if j==100:
      print(i)

keyroll({'eva':100,'aadi':50})

eva

Q WA function to list of strings as parameter and print all strings which have character 's' 2 times

In [36]:
def fn1(l):
  for i in l:
    if i.count('s')==2:
      print(i)

ll=['eva','wall-e','ss','ss rajmauli']
fn1(ll)

ss
ss rajmauli

Q WA function to take list of dictionaries. Print all dictionaries which contain key "id".

In [40]:
def funct(l):
  for dicts in l:
    for key,value in dicts.items():
      if key=='id':
        print(dicts)


list_of_dicts = [
    {"name": "John", "id": 1, "age": 25},
    {"name": "Jane", "age": 30},
    {"id": 2, "city": "New York"},
    {"username": "user123", "email": "user@example.com"}]
funct(list_of_dicts)

{'name': 'John', 'id': 1, 'age': 25}
{'id': 2, 'city': 'New York'}

Q. WA function to check if no is armstrong or not .

In [10]:
def armstrong(number):
  length=len(str(number))
  sum=0
  length=len(str(number))
  sum=0
  while number>0:
    rem=number%10
    number=number//10
    sum=sum+rem**length
  return sum

num=1634
print(armstrong(num))

1634