Write programs using lists in python
1. Reverse a given list in Python
aList = [100, 200, 300, 400, 500]
output:
[500, 400, 300, 200, 100]

In [ ]:
l=[100, 200, 300, 400, 500]
print(l[::-1])
l.reverse()
l

[500, 400, 300, 200, 100]

[500, 400, 300, 200, 100]

2. take a list 'l1' of even nos between 150 to 250. Print its length.
Then create another list 'l2' using 'l1', containing only nos divisible by 4 from 'l1'.

In [ ]:
l1=[]
for i in range (150,251,2):
  l1.append(i)

print(l1)

l2=[o for o in l1 if o%4==0]
print(l2)

[150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206, 208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232, 234, 236, 238, 240, 242, 244, 246, 248, 250]
[152, 156, 160, 164, 168, 172, 176, 180, 184, 188, 192, 196, 200, 204, 208, 212, 216, 220, 224, 228, 232, 236, 240, 244, 248]

3. Given a Python list of numbers. Turn every item of a list into its square root
aList = [1, 4, 9, 16, 25, 36, 49]
output:
[1, 2, 3, 4, 5, 6, 7]

In [ ]:
import math
List = [1, 4, 9, 16, 25, 36, 49]
l3=[int(math.sqrt(a)) for a in List ]
print(l3)

[1, 2, 3, 4, 5, 6, 7]

4. Print two lists in the following order
list1 = [5, 6,7]
list2 = [0, 1]
output:
50,51,60,61,70,71

In [ ]:
l1 = [5, 6,7]
l2 = [0, 1]
l3=[]
a=0
for i in l1:
  for j in l2:
    print(f'{i}{j}',end=",")

50,51,60,61,70,71,

In [ ]:
a=0
for e1 in l1:
    for e2 in l2:
        a=str(e1)+str(e2)
        l3.append(a)

print(l3)

['50', '51', '60', '61', '70', '71']

5. Given a two Python list. Iterate both lists simultaneously such that list1 should display item in original order and list2 in reverse order. It should work for any two lists.
list1 = [10, 20, 30, 40]
list2 = [100, 200, 300, 400]
output:
10 400
20 300
30 200
40 100

In [ ]:
list1 = [10, 20, 30, 40]
list2 = [100, 200, 300, 400]
list2.reverse()

for i,j in zip(list1,list2):
  print(i,j)

10 400
20 300
30 200
40 100

6. Remove empty strings from the list of strings
list1 = ["Ashish", "", "Atharva", "Amit", "", "Revati"]
output:
["Ashish", "Atharva", "Amit", "Revati"]

In [ ]:
list1 = ["Ashish", "", "Atharva", "Amit", "", "Revati"]
list1.remove('')
list1.remove('')
list1

['Ashish', 'Atharva', 'Amit', 'Revati']

7. Add item 7000 after 6000 in the following Python List
list1 = [10, 20, [300, 400, [5000, 6000], 500], 30, 40]
output:
[10, 20, [300, 400, [5000, 6000, 7000], 500], 30, 40]

In [ ]:
list1 = [10, 20, [300, 400, [5000, 6000], 500], 30, 40]
list1[2][2].append(7000)
list1

[10, 20, [300, 400, [5000, 6000, 7000], 500], 30, 40]

8. Given a nested list extend it by adding the sub list ["h", "i", "j"] in such a way that it will look like the following list

list1 = ["a", "b", ["c", ["d", "e", ["f", "g"], "k"], "l"], "m", "n"]
Sub List to be added = ["h", "i", "j"]
output:
['a', 'b', ['c', ['d', 'e', ['f', 'g', 'h', 'i', 'j'], 'k'], 'l'], 'm', 'n']

In [ ]:
list1 = ["a", "b", ["c", ["d", "e", ["f", "g"], "k"], "l"], "m", "n"]
s_list = ["h", "i", "j"]

list1[2][1][2].append(s_list)
list1

['a', 'b', ['c', ['d', 'e', ['f', 'g', ['h', 'i', 'j']], 'k'], 'l'], 'm', 'n']

In [ ]:
list1 = ["a", "b", ["c", ["d", "e", ["f", "g"], "k"], "l"], "m", "n"]
subList = ["h", "i", "j"]
list1[2][1][2].extend(subList)
print(list1)

['a', 'b', ['c', ['d', 'e', ['f', 'g', 'h', 'i', 'j'], 'k'], 'l'], 'm', 'n']

9. Given a Python list, find value 20 in the list, and if it is present, replace it with 200. Only update the first occurrence of a value
list1 = [5, 10, 15, 20, 25, 50, 20]
output:
list1 = [5, 10, 15, 200, 25, 50, 20]

In [ ]:
list1 = [5, 10, 15, 20, 25, 50, 20]
for i in range(len(list1)):
  if list1[i]==200:
    list1[i]=20
    break

list1

[5, 10, 15, 20, 25, 50, 20]

In [ ]:
index = list1.index(200)
list1[index]=20
list1

[5, 10, 15, 20, 25, 50, 20]

10. Given a Python list, remove all occurrence of 20 from the list
list1 = [5, 20, 15, 20, 25, 50, 20]
output:
[5, 15, 25, 50]

In [ ]:
list1 = [5, 20, 15, 20, 25, 50, 20]
ele=20
list2 = [o for o in list1 if o!=20]
list2

[5, 15, 25, 50]

In [ ]:
list4 = [5, 20, 15, 20, 25, 50, 20]
for i in list4:
  if i==20:
    list4.remove(20)

list4

[5, 15, 25, 50]

11. Take a number as input from user.
Print maximum and minimum integer which can be generated using all the digits in the input number
Ex. Input 3421   : o/p max: 4321, min 1234
Input 7789    : o/p max: 9776   min 6779

In [ ]:
num=3421
l_num=list(str(num))
l_num.sort()
print("".join(l_num))
l_num.sort(reverse=True)
print("".join(l_num))

1234
4321

12. Take integer from user and print all odd numbers which can be generated using any number of digits from given number
Ex.
Input: 3421  o/p: 1,3,13,43,23,31,41,21,421,241,341,431,423,243,143,413,1243,1423,4213,4123, 2413,2143, .. etc

In [116]:
n=int(input("enter the number"))

s=str(n)
l=list(s)
print(l)
l1=[]
from itertools import permutations
for i in range(1,len(l)+1):
  p1=permutations(l,i)
  for j in p1:
    l1.append(''.join(list(j)))
  l1=list(map(lambda x:int(x),l1))

  l2=list(filter(lambda x: x%2!=0,l1))

enter the number654
['6', '5', '4']

In [117]:
l2

[5, 65, 45, 645, 465]

In [127]:
kl=[1,2,3,4]

In [128]:
p2=permutations(kl,3)

In [129]:
ll=[]
for i in p2:
  ll.append(list(i))

In [134]:
for i in

In [136]:
ll

['[1, 2, 3]',
 '[1, 2, 4]',
 '[1, 3, 2]',
 '[1, 3, 4]',
 '[1, 4, 2]',
 '[1, 4, 3]',
 '[2, 1, 3]',
 '[2, 1, 4]',
 '[2, 3, 1]',
 '[2, 3, 4]',
 '[2, 4, 1]',
 '[2, 4, 3]',
 '[3, 1, 2]',
 '[3, 1, 4]',
 '[3, 2, 1]',
 '[3, 2, 4]',
 '[3, 4, 1]',
 '[3, 4, 2]',
 '[4, 1, 2]',
 '[4, 1, 3]',
 '[4, 2, 1]',
 '[4, 2, 3]',
 '[4, 3, 1]',
 '[4, 3, 2]']